version: '3'
services:
  cnn-ecs-50:
    build:
      context: .
      dockerfile: Dockerfile.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python /app/Fastapi_with_registration.py